spring:
  application:
    name: HotWheelsCollection
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/hotwheels}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/auth/realms/hotwheels/protocol/openid_connect/certs}

server:
  port: ${PORT:8080}

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: http://localhost:8000
    table-name: ${DYNAMODB_TABLE_NAME:hot-wheels-collection}
